<?php

namespace Botter;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Controller\ControllerResolver as Resolver;

class ControllerResolver extends Resolver
{
    /**
     * @var ContainerBuilder
     */
    private $container;

    public function __construct(ContainerBuilder $containerBuilder)
    {
        $this->container = $containerBuilder;
        parent::__construct();
    }

    /**
     * @param string $class
     * @return object
     */
    protected function instantiateController($class)
    {
        $controller = parent::instantiateController($class); // TODO: Change the autogenerated stub
        if ($controller instanceof ContainerAwareInterface) {
            $controller->setContainer($this->container);
        }
        return $controller;
    }
}